package com.interviewdot.AWSDynamoDB.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.io.Serializable

@DynamoDBTable(tableName = "employee")
class Employee : Serializable {
    private val serialVersionUID = 1L

    private var employeeId: String? = null
    private var firstName: String? = null
    private var lastName: String? = null
    private var age: String? = null
    private var address: Address? = null

    @DynamoDBHashKey(attributeName = "employeeId")
    @DynamoDBAutoGeneratedKey
    fun getEmployeeId(): String? {
        return employeeId
    }

    fun setEmployeeId(employeeId: String) {
        this.employeeId = employeeId
    }

    @DynamoDBAttribute
    fun getFirstName(): String? {
        return firstName
    }

    fun setFirstName(firstName: String) {
        this.firstName = firstName
    }

    @DynamoDBRangeKey
    fun getLastName(): String? {
        return lastName
    }

    fun setLastName(lastName: String) {
        this.lastName = lastName
    }

    @DynamoDBAttribute
    fun getAge(): String? {
        return age
    }

    fun setAge(age: String) {
        this.age = age
    }

    @DynamoDBAttribute
    fun getAddress(): Address? {
        return address
    }

    fun setAddress(address: Address) {
        this.address = address
    }
}